name: GitHub Action for SBOM Generation using Syft
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Package Frontend
      run: |
        docker build -t test-image .
    - uses: anchore/sbom-action@v0
      with: 
        image: test-image:latest
        artifact-name: report.spdx-json
        output-file: ./report.spdx-json
    
    - uses: anchore/sbom-action/publish-sbom@v0
      with:
        sbom-artifact-match: ".*\\.spdx$"    

    - name: cat
      run: |
        pwd
        ls
        cat report.spdx-json
